name: hotel_order_taking_app
description: A restaurant order management system with Firebase backend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.0

  # State Management
  provider: ^6.1.2

  # PDF Generation
  pdf: ^3.11.1
  path_provider: ^2.1.5

  # Sharing & Communication
  share_plus: ^10.1.2
  url_launcher: ^6.3.1

  # QR Code Scanner
  mobile_scanner: ^5.2.3

  # Date Formatting
  intl: ^0.19.0

  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true